### ISSUE TITLE
Update documentation to use specific variable names

### ISSUE THREAD

**Issue by Chris-Boyle** [docusign/code-examples-node#22]
[When following the README the JWT section](https://github.com/docusign/code-examples-node#configuring-jwt) says we need to update some variables in the appsettings.json file.  It doesn't say what those variables are in the file.  It also doesn't say what they are called on the [api-integrator-key page on the Docusign site](https://admindemo.docusign.com/api-integrator-key).  It would be really helpful to have a clear mapping of what the values are in the appsettings.json file and precisely what they are called in the api-integrator-key page.  This makes it difficult to get the test app up and running.

**Comment by dmartin00** [comment]
Hello Chris,

Thanks for the feedback. I've filed ticket DEVDOCS-3867 to have that updated.
Were you able to get the example up and running or are you still having issues?

**Comment by Chris-Boyle** [comment]
@dmartin00 i was not able to but I did get all the js APIs working eventually in my app.

**Comment by meihDS** [comment]
Hi Chris, I independently updated the Node README with these instructions the day after you posted the comment. Please let us know if there's additional info needed. Also, I created a Node Quickstart video https://youtu.be/5iUq00IRaTk that maps the values in the appsettings.json file to the api-integrator-key page at 2:52

**Comment by InbarGazit** [comment]
@Chris-Boyle  can we close this?

**Comment by Chris-Boyle** [comment]
@InbarGazit yes.  Thank you all!

**Comment by ivdinkovds** [comment]
Closing the case
