### ISSUE TITLE
How to create Date Signed Tab (Text Field) in the HTML template 

### ISSUE THREAD

**Issue by gaurij369** [docusign/code-examples-node#24]
There is no example with regards to this in the Node SDK example list. Also can I add a date picker? Please do reply as I am unable to figure this out and I am looking for a while.

**Comment by ivdinkovds** [comment]
Hi @gaurij369 you can add "Date Signed" in Node using the snippet below 
`       let dateSignedTab1 = docusign.DateSigned.constructFromObject({
          anchorString: "signer1date",  
          anchorYOffset: "-6",  
          fontSize: "Size12",  
          name: "Date Signed",  
          recipientId: "1",  
          tabLabel: "date_signed" 
        });`
The date tab is automatically populated when the signer signs the document. You can not control this date as this is part of the signing process.

Regrading a datepicker tab, currently there is no such functionality. 

As alternative to datepicker tab, you can integrate datepicker in your front end, collect the date and populate text field tab. something like
`        textCutomDate = docusign.Text.constructFromObject({
            anchorString: '/custom_date/', anchorUnits: 'pixels',
            anchorYOffset: '-9', anchorXOffset: '5',
            font: 'helvetica', fontSize: 'size11',
            bold: 'true', 
            value: date_collected_from_datepicker,
            locked: 'false', tabId: 'custom_date_id',
            tabLabel: 'Custom date'
        })`
