### ISSUE TITLE
Not able to update text tab value using updateTabs API

### ISSUE THREAD

**Issue by chanakyap** [docusign/code-examples-node#26]
I am trying to update the value of text tabs of an envelope, so i am using envelopesAPI.listTabs api to get all values, and envelopesApi.updateTabs  to update them, but i keep getting error 'The request body is missing or improperly formatted. No tabs specified'.  Can anyone provide example code to update textTabs?

**Comment by InbarGazit** [comment]
Hello @chanakyap  sorry for the delay, can you share the code that gives you an issue please?

**Comment by chanakyap** [comment]
@InbarGazit, the issue is resolved. I am sending wrong params (templateTabs instead of just tabs).
