### ISSUE TITLE
/config/appsettings.json: Description of required variables

### ISSUE THREAD

**Issue by jeff00seattle** [docusign/code-examples-node#29]
https://github.com/docusign/code-examples-node/blob/master/config/appsettings.example.json

**/config/appsettings.example.json**: This may be obvious for most, but it would be helpful to provide a brief description and link to the DocuSign Developer authentication online documentation.

```
dsClientId: "{INTEGRATION_KEY_AUTH_CODE}",
dsClientSecret: "{SECRET_KEY}",
dsJWTClientId: "{INTEGRATION_KEY_JWT}",
impersonatedUserGuid: "{IMPERSONATED_USER_ID}",
signerEmail: "{SIGNER_EMAIL}",
signerName: "{SIGNER_NAME}",
gatewayAccountId: "{GATEWAY_ACCOUNT_ID}",
quickstart: "{QUICKSTART_VALUE}",
```

**Comment by InbarGazit** [comment]
@jeff00seattle  the README does explain how to manually update this file, but the Quickstart does it for you automatically...
