### ISSUE TITLE
How to cancel an envelope

### ISSUE THREAD

**Issue by kouayip** [docusign/code-examples-node#33]
I want to cancel or delete an envelope

**Comment by InbarGazit** [comment]
https://www.docusign.com/blog/dsdev-common-api-tasks-void-an-envelope

**Comment by InbarGazit** [comment]
You need to know the envelopeId, and then you make a call to update the status

**Comment by InbarGazit** [comment]
Let me know if you have further questions, or we can close this issue.

**Comment by kouayip** [comment]
thk
