### ISSUE TITLE
How do I change phone numbers when using templates to generate envelopes 

### ISSUE THREAD

**Issue by shengbid** [docusign/code-examples-node#40]
Create templates that require phone validation. How do I change phone numbers when using templates to generate envelopes 
![image](https://user-images.githubusercontent.com/35691811/173976581-e3bd5467-8088-46a8-830f-5a4ef39ee000.png)

![image](https://user-images.githubusercontent.com/35691811/173976681-42147e85-e226-45a2-966c-38eca2355141.png)

Is there any interface that can modify the recipient as templateRoles does ?

**Comment by InbarGazit** [comment]
See https://developers.docusign.com/docs/esign-rest-api/how-to/phone-auth/
The node code for a recipient is like this:

```
let signer1 = docusign.Signer.constructFromObject({
    email: args.signerEmail,
    name: args.signerName,
    recipientId: "1",
    routingOrder: "1",
    deliveryMethod: "Email",
    tabs: signer1Tabs,
    identityVerification: { workflowId: args.workflowId, steps: null, "inputOptions":[{"name":"phone_number_list","valueType":"PhoneNumberList","phoneNumberList":[{"countryCode":args.countryCode,"code":"1","number":args.phoneNumber}]}], "idCheckConfigurationName":""}
```

**Comment by InbarGazit** [comment]
Just replace the `Signer` object with a `TemplateRole` object, but the rest should be the same.

**Comment by shengbid** [comment]
How do I get signer1Tabs content?  I want to generate the envelope with the defined template

**Comment by shengbid** [comment]
How do I get signer1Tabs content?&nbsp; I want to generate the envelope with the defined template&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "docusign/code-examples-node"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [docusign/code-examples-node] How do I change phone numbers when using templates to generate envelopes  (Issue #40)





 
Just replace the Signer object with a TemplateRole object, but the rest should be the same.

**Comment by shengbid** [comment]
![image](https://user-images.githubusercontent.com/35691811/173980926-ee8855c2-f49b-444e-b4d7-8fe798387d15.png)

**Comment by InbarGazit** [comment]
The last error occurs because you're using a **templateId** which requires **templateRole** so you cannot specify **recipients** too.
I would recommend using the composite template model that allow the most flexibility.

**Comment by InbarGazit** [comment]
Let us know if you still need help on this
