### ISSUE TITLE
Module not found - '../config/examplesApi.json'

### ISSUE THREAD

**Issue by paulrmatei** [docusign/code-examples-node#43]
File is currently called examplesAPI.json.
Easiest fix would be renaming the file

**Comment by sylvainleb376** [comment]
Do you have a question or issue? If required could you please elaborate and give more context?
Thanks

**Comment by paulrmatei** [comment]
Downloaded the code and ran `npm install`
Running `npm start` throws an error `Error: Cannot find module '../config/examplesApi.json'`

![image](https://user-images.githubusercontent.com/53083842/181757995-8c7032d1-da71-4cb1-a80b-2101ab1a9200.png)


Current file is called examplesAPI.json
Renaming the file to examplesApi.json fixed it for me

**Comment by sylvainleb376** [comment]
Sounds like a bug.
I raise it to our Engineering team. Meanwhile you can continue using the workaround you've found.
Thank you for your message

**Comment by pmackle** [comment]
Fixed in https://github.com/docusign/code-examples-node/pull/44
