### ISSUE TITLE
npm install fails due to package-lock.json pointing to local file

### ISSUE THREAD

**Issue by tylercollier** [docusign/code-examples-node#58]
```
$ npm i
...
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/tylercollier/repos/code-examples-node/docusign-webforms-1.0.2-rc11.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/tylercollier/repos/code-examples-node/docusign-webforms-1.0.2-rc11.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Looks like it happened here. https://github.com/docusign/code-examples-node/commit/796a3f7d2e6868b87067898b91022df89175b6bb

Not sure why a local file was committed.

**Comment by InbarGazit** [comment]
@tylercollier can you try again now?

**Comment by tylercollier** [comment]
I didn't try again. Instead I just looked at your changes which look fine. Hopefully your change affects what's bundled into the Quickstart example zip files.
